import os
import sys
import argparse
import socket
import signal
import uvicorn
import psutil
from typing import Optional

def get_process_holding_port(port: int) -> Optional[psutil.Process]:
    """
    Finds the process listening on the specified port.
    """
    try:
        for conn in psutil.net_connections(kind='inet'):
            if conn.laddr.port == port and conn.status == 'LISTEN':
                return psutil.Process(conn.pid)
    except Exception:
        pass
    return None

def safe_clear_port(port: int) -> bool:
    """
    Checks the target port. If occupied by a stale catcut/uvicorn process, terminates it.
    Returns True if the port is now free, False if it is occupied by a foreign process.
    """
    proc = get_process_holding_port(port)
    if not proc:
        return True # Port is free
        
    try:
        pid = proc.pid
        name = proc.name().lower()
        cmdline = " ".join(proc.cmdline()).lower()
        
        # Don't kill ourselves
        if pid == os.getpid():
            return True
            
        # Signature check: Is it python running uvicorn/main.py/catcut?
        is_python = "python" in name or "python" in cmdline
        is_catcut = "uvicorn" in cmdline or "main.py" in cmdline or "catcut" in cmdline
        
        if is_python and is_catcut:
            print(f"⚠️ Port {port} is held by a stale catcut backend (PID: {pid}). Terminating it...")
            proc.terminate()
            try:
                proc.wait(timeout=3)
                print(f"✅ Stale process {pid} terminated successfully.")
                return True
            except psutil.TimeoutExpired:
                print(f"🔥 Process {pid} did not respond. Killing it forceably...")
                proc.kill()
                proc.wait()
                print(f"✅ Stale process {pid} killed.")
                return True
        else:
            print(f"ℹ️ Port {port} is occupied by another application: '{name}' (PID: {pid}).")
            return False
            
    except (psutil.NoSuchProcess, psutil.AccessDenied) as e:
        print(f"🔒 Insufficient permissions to manage process on port {port}: {e}")
        return False

def find_free_port(start_port: int) -> int:
    """
    Scans ports starting from start_port and returns the first free port.
    """
    port = start_port
    while True:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("127.0.0.1", port))
                return port
            except OSError:
                port += 1

def sync_frontend_env(port: int):
    """
    Writes the backend API URL config into Next.js frontend's .env.local file.
    This enables dynamic backend port discovery for the frontend.
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    frontend_dir = os.path.abspath(os.path.join(current_dir, "../catcut-frontend"))
    
    if not os.path.exists(frontend_dir):
        print("⚠️ Warning: catcut-frontend folder not found. Next.js env sync skipped.")
        return
        
    env_file = os.path.join(frontend_dir, ".env.local")
    try:
        with open(env_file, "w") as f:
            f.write(f"# Generated by catcut backend on startup\n")
            f.write(f"NEXT_PUBLIC_API_URL=http://localhost:{port}\n")
        print(f"⚙️ Synchronized backend port in frontend configuration: {env_file}")
    except Exception as e:
        print(f"⚠️ Failed to write frontend .env.local: {e}")

def main():
    parser = argparse.ArgumentParser(description="catcut FastAPI Backend Launcher")
    parser.add_argument("--host", type=str, default="127.0.0.1", help="Host address to bind to")
    parser.add_argument("--port", type=int, default=8000, help="Preferred port for the backend API")
    args = parser.parse_args()
    
    preferred_port = args.port
    actual_port = preferred_port
    
    print("=" * 60)
    print("🐱 catcut — Backend startup check")
    print("=" * 60)
    
    # Try to clear preferred port if occupied by stale catcut process
    port_is_free = safe_clear_port(preferred_port)
    
    if not port_is_free:
        # If occupied by a different app, scan for a free port
        actual_port = find_free_port(preferred_port)
        print(f"🔄 Port {preferred_port} is busy. Found next available port: {actual_port}")
        
    # Write the actual port to frontend's configuration
    sync_frontend_env(actual_port)
    
    print("-" * 60)
    print(f"🎉 Catcut backend is running on: http://{args.host}:{actual_port}")
    print(f"📖 Swagger docs API portal:   http://{args.host}:{actual_port}/docs")
    print("-" * 60)
    print("💡 To launch the frontend, run in another terminal:")
    print("   cd catcut/catcut-frontend")
    print("   npm run dev")
    print("=" * 60)
    
    # Run uvicorn server
    uvicorn.run("app.main:app", host=args.host, port=actual_port, reload=True)

if __name__ == "__main__":
    main()
